// <auto-generated />
using System;
using F1_Fantasy_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace F1_Fantasy_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251228134348_initial migration1")]
    partial class initialmigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Constructor", b =>
                {
                    b.Property<int>("ConstructorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConstructorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ConstructorId");

                    b.ToTable("Constructor");

                    b.HasData(
                        new
                        {
                            ConstructorId = 1,
                            Name = "McLaren"
                        },
                        new
                        {
                            ConstructorId = 2,
                            Name = "Red Bull"
                        },
                        new
                        {
                            ConstructorId = 3,
                            Name = "Mercedes"
                        },
                        new
                        {
                            ConstructorId = 4,
                            Name = "Ferrari"
                        },
                        new
                        {
                            ConstructorId = 5,
                            Name = "Aston Martin"
                        },
                        new
                        {
                            ConstructorId = 6,
                            Name = "Williams"
                        },
                        new
                        {
                            ConstructorId = 7,
                            Name = "Racing Bulls"
                        },
                        new
                        {
                            ConstructorId = 8,
                            Name = "Haas F1 Team"
                        },
                        new
                        {
                            ConstructorId = 9,
                            Name = "Kick Sauber"
                        },
                        new
                        {
                            ConstructorId = 10,
                            Name = "Alpine"
                        });
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.ConstructorSelection", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("RaceId", "ConstructorId", "TeamId");

                    b.HasIndex("ConstructorId");

                    b.HasIndex("TeamId");

                    b.ToTable("ConstructorSelection");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<int>("ConstructorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("ConstructorId");

                    b.ToTable("Driver");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            ConstructorId = 1,
                            Name = "Lando Norris",
                            Price = 58
                        },
                        new
                        {
                            DriverId = 2,
                            ConstructorId = 1,
                            Name = "Oscar Piastri",
                            Price = 50
                        },
                        new
                        {
                            DriverId = 3,
                            ConstructorId = 2,
                            Name = "Max Verstappen",
                            Price = 60
                        },
                        new
                        {
                            DriverId = 4,
                            ConstructorId = 2,
                            Name = "Yuki Tsunoda",
                            Price = 30
                        },
                        new
                        {
                            DriverId = 5,
                            ConstructorId = 3,
                            Name = "George Russell",
                            Price = 48
                        },
                        new
                        {
                            DriverId = 6,
                            ConstructorId = 3,
                            Name = "Andrea Kimi Antonelli",
                            Price = 21
                        },
                        new
                        {
                            DriverId = 7,
                            ConstructorId = 4,
                            Name = "Charles Leclerc",
                            Price = 56
                        },
                        new
                        {
                            DriverId = 8,
                            ConstructorId = 4,
                            Name = "Lewis Hamilton",
                            Price = 55
                        },
                        new
                        {
                            DriverId = 9,
                            ConstructorId = 5,
                            Name = "Fernando Alonso",
                            Price = 40
                        },
                        new
                        {
                            DriverId = 10,
                            ConstructorId = 5,
                            Name = "Lance Stroll",
                            Price = 26
                        },
                        new
                        {
                            DriverId = 11,
                            ConstructorId = 6,
                            Name = "Alex Albon",
                            Price = 38
                        },
                        new
                        {
                            DriverId = 12,
                            ConstructorId = 6,
                            Name = "Carlos Sainz",
                            Price = 47
                        },
                        new
                        {
                            DriverId = 13,
                            ConstructorId = 7,
                            Name = "Liam Lawson",
                            Price = 22
                        },
                        new
                        {
                            DriverId = 14,
                            ConstructorId = 7,
                            Name = "Isack Hadjar",
                            Price = 16
                        },
                        new
                        {
                            DriverId = 15,
                            ConstructorId = 8,
                            Name = "Esteban Ocon",
                            Price = 28
                        },
                        new
                        {
                            DriverId = 16,
                            ConstructorId = 8,
                            Name = "Oliver Bearman",
                            Price = 20
                        },
                        new
                        {
                            DriverId = 17,
                            ConstructorId = 9,
                            Name = "Nico Hulkenberg",
                            Price = 27
                        },
                        new
                        {
                            DriverId = 18,
                            ConstructorId = 9,
                            Name = "Gabriel Bortoleto",
                            Price = 18
                        },
                        new
                        {
                            DriverId = 19,
                            ConstructorId = 10,
                            Name = "Pierre Gasly",
                            Price = 36
                        },
                        new
                        {
                            DriverId = 20,
                            ConstructorId = 10,
                            Name = "Franco Colapinto",
                            Price = 15
                        });
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.DriverRaceResult", b =>
                {
                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("Points")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("DriverId", "RaceId");

                    b.HasIndex("RaceId");

                    b.ToTable("DriverRaceResult");

                    b.HasData(
                        new
                        {
                            DriverId = 1,
                            RaceId = 1,
                            Points = 25,
                            Position = 1
                        },
                        new
                        {
                            DriverId = 3,
                            RaceId = 1,
                            Points = 18,
                            Position = 2
                        },
                        new
                        {
                            DriverId = 5,
                            RaceId = 1,
                            Points = 15,
                            Position = 3
                        },
                        new
                        {
                            DriverId = 6,
                            RaceId = 1,
                            Points = 12,
                            Position = 4
                        },
                        new
                        {
                            DriverId = 11,
                            RaceId = 1,
                            Points = 10,
                            Position = 5
                        },
                        new
                        {
                            DriverId = 10,
                            RaceId = 1,
                            Points = 8,
                            Position = 6
                        },
                        new
                        {
                            DriverId = 17,
                            RaceId = 1,
                            Points = 6,
                            Position = 7
                        },
                        new
                        {
                            DriverId = 7,
                            RaceId = 1,
                            Points = 4,
                            Position = 8
                        },
                        new
                        {
                            DriverId = 2,
                            RaceId = 1,
                            Points = 2,
                            Position = 9
                        },
                        new
                        {
                            DriverId = 8,
                            RaceId = 1,
                            Points = 1,
                            Position = 10
                        },
                        new
                        {
                            DriverId = 19,
                            RaceId = 1,
                            Points = 0,
                            Position = 11
                        },
                        new
                        {
                            DriverId = 4,
                            RaceId = 1,
                            Points = 0,
                            Position = 12
                        },
                        new
                        {
                            DriverId = 15,
                            RaceId = 1,
                            Points = 0,
                            Position = 13
                        },
                        new
                        {
                            DriverId = 16,
                            RaceId = 1,
                            Points = 0,
                            Position = 14
                        },
                        new
                        {
                            DriverId = 2,
                            RaceId = 2,
                            Points = 25,
                            Position = 1
                        },
                        new
                        {
                            DriverId = 1,
                            RaceId = 2,
                            Points = 18,
                            Position = 2
                        },
                        new
                        {
                            DriverId = 5,
                            RaceId = 2,
                            Points = 15,
                            Position = 3
                        },
                        new
                        {
                            DriverId = 3,
                            RaceId = 2,
                            Points = 12,
                            Position = 4
                        },
                        new
                        {
                            DriverId = 15,
                            RaceId = 2,
                            Points = 10,
                            Position = 5
                        },
                        new
                        {
                            DriverId = 6,
                            RaceId = 2,
                            Points = 8,
                            Position = 6
                        },
                        new
                        {
                            DriverId = 11,
                            RaceId = 2,
                            Points = 6,
                            Position = 7
                        },
                        new
                        {
                            DriverId = 16,
                            RaceId = 2,
                            Points = 4,
                            Position = 8
                        },
                        new
                        {
                            DriverId = 10,
                            RaceId = 2,
                            Points = 2,
                            Position = 9
                        },
                        new
                        {
                            DriverId = 12,
                            RaceId = 2,
                            Points = 1,
                            Position = 10
                        });
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.DriverSelection", b =>
                {
                    b.Property<int>("RaceId")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsTurbo")
                        .HasColumnType("bit");

                    b.HasKey("RaceId", "DriverId", "TeamId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TeamId");

                    b.ToTable("DriverSelection");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Race", b =>
                {
                    b.Property<int>("RaceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaceId"));

                    b.Property<string>("CircuitName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Laps")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Season")
                        .HasColumnType("int");

                    b.HasKey("RaceId");

                    b.ToTable("Race");

                    b.HasData(
                        new
                        {
                            RaceId = 1,
                            CircuitName = "Albert Park Grand Prix Circuit",
                            Date = new DateTime(2025, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 57,
                            Name = "Australian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 2,
                            CircuitName = "Shanghai International Circuit",
                            Date = new DateTime(2025, 3, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 56,
                            Name = "Chinese Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 3,
                            CircuitName = "Suzuka Circuit",
                            Date = new DateTime(2025, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 53,
                            Name = "Japanese Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 4,
                            CircuitName = "Bahrain International Circuit",
                            Date = new DateTime(2025, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 57,
                            Name = "Bahrain Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 5,
                            CircuitName = "Jeddah Corniche Circuit",
                            Date = new DateTime(2025, 4, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 50,
                            Name = "Saudi Arabian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 6,
                            CircuitName = "Miami International Autodrome",
                            Date = new DateTime(2025, 5, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 57,
                            Name = "Miami Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 7,
                            CircuitName = "Autodromo Enzo e Dino Ferrari",
                            Date = new DateTime(2025, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 63,
                            Name = "Emilia Romagna Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 8,
                            CircuitName = "Circuit de Monaco",
                            Date = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 78,
                            Name = "Monaco Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 9,
                            CircuitName = "Circuit de Barcelona-Catalunya",
                            Date = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 66,
                            Name = "Spanish Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 10,
                            CircuitName = "Circuit Gilles Villeneuve",
                            Date = new DateTime(2025, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 70,
                            Name = "Canadian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 11,
                            CircuitName = "Red Bull Ring",
                            Date = new DateTime(2025, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 71,
                            Name = "Austrian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 12,
                            CircuitName = "Silverstone Circuit",
                            Date = new DateTime(2025, 7, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 52,
                            Name = "British Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 13,
                            CircuitName = "Circuit de Spa-Francorchamps",
                            Date = new DateTime(2025, 7, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 44,
                            Name = "Belgian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 14,
                            CircuitName = "Hungaroring",
                            Date = new DateTime(2025, 8, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 70,
                            Name = "Hungarian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 15,
                            CircuitName = "Circuit Park Zandvoort",
                            Date = new DateTime(2025, 8, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 72,
                            Name = "Dutch Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 16,
                            CircuitName = "Autodromo Nazionale di Monza",
                            Date = new DateTime(2025, 9, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 53,
                            Name = "Italian Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 17,
                            CircuitName = "Baku City Circuit",
                            Date = new DateTime(2025, 9, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 51,
                            Name = "Azerbaijan Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 18,
                            CircuitName = "Marina Bay Street Circuit",
                            Date = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 62,
                            Name = "Singapore Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 19,
                            CircuitName = "Circuit of the Americas",
                            Date = new DateTime(2025, 10, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 56,
                            Name = "United States Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 20,
                            CircuitName = "Autódromo Hermanos Rodríguez",
                            Date = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 71,
                            Name = "Mexico City Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 21,
                            CircuitName = "Autódromo José Carlos Pace",
                            Date = new DateTime(2025, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 71,
                            Name = "São Paulo Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 22,
                            CircuitName = "Las Vegas Strip Street Circuit",
                            Date = new DateTime(2025, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 50,
                            Name = "Las Vegas Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 23,
                            CircuitName = "Losail International Circuit",
                            Date = new DateTime(2025, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 57,
                            Name = "Qatar Grand Prix",
                            Season = 2025
                        },
                        new
                        {
                            RaceId = 24,
                            CircuitName = "Yas Marina Circuit",
                            Date = new DateTime(2025, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Laps = 58,
                            Name = "Abu Dhabi Grand Prix",
                            Season = 2025
                        });
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Team");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("Balance")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.ConstructorSelection", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.Constructor", "Constructor")
                        .WithMany("ConstructorSelections")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.Race", "Race")
                        .WithMany("ConstructorSelections")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.Team", "Team")
                        .WithMany("ConstructorSelections")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");

                    b.Navigation("Race");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Driver", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.Constructor", "Constructor")
                        .WithMany("Drivers")
                        .HasForeignKey("ConstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Constructor");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.DriverRaceResult", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.Driver", "Driver")
                        .WithMany("DriverRaceResults")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.Race", "Race")
                        .WithMany("DriverRaceResults")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.DriverSelection", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.Driver", "Driver")
                        .WithMany("DriverSelections")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.Race", "Race")
                        .WithMany("DriverSelections")
                        .HasForeignKey("RaceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.Team", "Team")
                        .WithMany("DriverSelections")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Race");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Team", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.User", "User")
                        .WithOne("Team")
                        .HasForeignKey("F1_Fantasy_API.Models.Entites.Team", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1_Fantasy_API.Models.Entites.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("F1_Fantasy_API.Models.Entites.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Constructor", b =>
                {
                    b.Navigation("ConstructorSelections");

                    b.Navigation("Drivers");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Driver", b =>
                {
                    b.Navigation("DriverRaceResults");

                    b.Navigation("DriverSelections");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Race", b =>
                {
                    b.Navigation("ConstructorSelections");

                    b.Navigation("DriverRaceResults");

                    b.Navigation("DriverSelections");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.Team", b =>
                {
                    b.Navigation("ConstructorSelections");

                    b.Navigation("DriverSelections");
                });

            modelBuilder.Entity("F1_Fantasy_API.Models.Entites.User", b =>
                {
                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
